apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}-grpc
  labels:
    runtime: grpc
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
