apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}-socket
  labels:
    runtime: socket
    {{- include "gateway.selectorLabels" . | nindent 4 }}
  annotations:
    # 会话保持需要性能保障型
    service.beta.kubernetes.io/alicloud-loadbalancer-spec: "slb.s3.small"
    service.beta.kubernetes.io/alicloud-loadbalancer-force-override-listeners: 'true'
    # hebeifen.com
    service.beta.kubernetes.io/alicloud-loadbalancer-id: lb-wz9wdxyk92t36xwy87ibj
    # service.beta.kubernetes.io/alicloud-loadbalancer-cert-id: "1158562227097523_16c5bb64604_1375155937_-1558881903"
    service.beta.kubernetes.io/alicloud-loadbalancer-protocol-port: "http:50520,http:50910"
    # http => https
    # service.beta.kubernetes.io/alicloud-loadbalancer-forward-port: "80:443"
    # 保持会话
    service.beta.kubernetes.io/alicloud-loadbalancer-sticky-session: "on"
    service.beta.kubernetes.io/alicloud-loadbalancer-sticky-session-type: "insert"
    service.beta.kubernetes.io/alicloud-loadbalancer-cookie-timeout: "86400"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http1
      port: 50520
      protocol: TCP
      targetPort: socket
    - name: http2
      port: 50910
      protocol: TCP
      targetPort: socket
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
